services:
  - type: web
    name: fin-track-api
    runtime: docker
    env: docker
    plan: free # or paid if needed
    build:
      context: .
      dockerfile: Dockerfile
    envVars:
      - key: DB_HOST
        valueFrom: db_host
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        valueFrom: db_password
      - key: DB_NAME
        value: fintrack
      - key: DB_PORT
        value: "3306"
    healthCheckPath: /health
    autoDeploy: true

  - type: mysql
    name: fin-track-db
    plan: free
    databaseName: fintrack
    user: root
    password: test@123 # Change to a stronger password!