apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: your-registry/fintrack:latest
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: fintrack-config
          - secretRef:
              name: fintrack-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
        volumeMounts:
          - name: logs
            mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}